/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UroosRouteImport } from './routes/uroos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeoStatusRouteImport } from './routes/seo-status'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MaqamRouteImport } from './routes/maqam'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as MaqamIdRouteImport } from './routes/maqam_.$id'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const UroosRoute = UroosRouteImport.update({
  id: '/uroos',
  path: '/uroos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoStatusRoute = SeoStatusRouteImport.update({
  id: '/seo-status',
  path: '/seo-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MaqamRoute = MaqamRouteImport.update({
  id: '/maqam',
  path: '/maqam',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaqamIdRoute = MaqamIdRouteImport.update({
  id: '/maqam_/$id',
  path: '/maqam/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/maqam': typeof MaqamRoute
  '/privacy': typeof PrivacyRoute
  '/seo-status': typeof SeoStatusRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uroos': typeof UroosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/maqam/$id': typeof MaqamIdRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/maqam': typeof MaqamRoute
  '/privacy': typeof PrivacyRoute
  '/seo-status': typeof SeoStatusRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uroos': typeof UroosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/maqam/$id': typeof MaqamIdRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/maqam': typeof MaqamRoute
  '/privacy': typeof PrivacyRoute
  '/seo-status': typeof SeoStatusRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uroos': typeof UroosRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/maqam_/$id': typeof MaqamIdRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/maqam'
    | '/privacy'
    | '/seo-status'
    | '/sitemap.xml'
    | '/uroos'
    | '/blog/$slug'
    | '/maqam/$id'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/maqam'
    | '/privacy'
    | '/seo-status'
    | '/sitemap.xml'
    | '/uroos'
    | '/blog/$slug'
    | '/maqam/$id'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/maqam'
    | '/privacy'
    | '/seo-status'
    | '/sitemap.xml'
    | '/uroos'
    | '/blog_/$slug'
    | '/maqam_/$id'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MaqamRoute: typeof MaqamRoute
  PrivacyRoute: typeof PrivacyRoute
  SeoStatusRoute: typeof SeoStatusRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UroosRoute: typeof UroosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MaqamIdRoute: typeof MaqamIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uroos': {
      id: '/uroos'
      path: '/uroos'
      fullPath: '/uroos'
      preLoaderRoute: typeof UroosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-status': {
      id: '/seo-status'
      path: '/seo-status'
      fullPath: '/seo-status'
      preLoaderRoute: typeof SeoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maqam': {
      id: '/maqam'
      path: '/maqam'
      fullPath: '/maqam'
      preLoaderRoute: typeof MaqamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maqam_/$id': {
      id: '/maqam_/$id'
      path: '/maqam/$id'
      fullPath: '/maqam/$id'
      preLoaderRoute: typeof MaqamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MaqamRoute: MaqamRoute,
  PrivacyRoute: PrivacyRoute,
  SeoStatusRoute: SeoStatusRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UroosRoute: UroosRoute,
  BlogSlugRoute: BlogSlugRoute,
  MaqamIdRoute: MaqamIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
